# Kubernetes デプロイメント設定
# kubectl apply -f k8s-deployment.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: vite-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
  namespace: vite-app
  labels:
    app: vite-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: your-registry/vite-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
  namespace: vite-app
  labels:
    app: vite-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: vite-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vite-app-ingress
  namespace: vite-app
  annotations:
    # Nginxの場合
    nginx.ingress.kubernetes.io/rewrite-target: /
    # SSL証明書の自動発行（cert-manager使用時）
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - your-domain.com
    secretName: vite-app-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vite-app-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vite-app-hpa
  namespace: vite-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vite-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
