import { HeaderNav } from "@/components/sections/HeaderNav";
import { Box } from "@/components/unit/Box";
import { createGlobalStyles } from "@/styles/globalStyles";
import { Global } from "@emotion/react";
import Head from "next/head";
import type { FC, ReactNode } from "react";

interface Props {
  children: ReactNode;
}
export const Default: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Nao Sasaki｜lanberb.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Global styles={createGlobalStyles} />
      </Head>
      <header>
        <HeaderNav />
      </header>
      <main>{children}</main>
    </>
  );
};
